// <auto-generated />
using System;
using GMC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GMC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GMC.Model.Address", b =>
                {
                    b.Property<string>("AddressID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Address1")
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("Address2")
                        .HasColumnType("varchar(MAX)");

                    b.Property<string>("AddressType")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("City")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ClientID")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CouncilId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone1")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Phone2")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("PlaceType")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("State")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Zip")
                        .HasColumnType("varchar(50)");

                    b.HasKey("AddressID");

                    b.ToTable("tbl_address");
                });

            modelBuilder.Entity("GMC.Model.BloodGroupTypeMaster", b =>
                {
                    b.Property<int?>("BloodGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("BloodGroupId"));

                    b.Property<string>("Active")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodGroupCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodGroupDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodGroupDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CouncilId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("BloodGroupId");

                    b.ToTable("tbl_blood_group_type_master");
                });

            modelBuilder.Entity("GMC.Model.CBAccountMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("AccountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CouncilId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tbl_CB_Account_Master");
                });

            modelBuilder.Entity("GMC.Model.CBGroupMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AutoGroupID")
                        .HasColumnType("int");

                    b.Property<string>("CouncilId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName_PDF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tbl_CB_Group_Master");
                });

            modelBuilder.Entity("GMC.Model.CaseWorker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CWUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CouncilId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tbl_case_workers");
                });

            modelBuilder.Entity("GMC.Model.College", b =>
                {
                    b.Property<string>("ColId")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("col_id");

                    b.Property<string>("ColAddress")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("col_address");

                    b.Property<string>("ColName")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("col_name");

                    b.Property<string>("CollegeCode")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("college_code");

                    b.Property<string>("CouncilId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("FirsttimeLogin")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Myid")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrincipalName")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("Principal_name");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TelNumber")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tel_number");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(25)")
                        .HasColumnName("type");

                    b.Property<string>("UniversityName")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("university_name");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Usercount")
                        .HasColumnType("int");

                    b.HasKey("ColId");

                    b.ToTable("tbl_colleges");
                });

            modelBuilder.Entity("GMC.Model.CountryMaster", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Active")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("tbl_J_Country_Master");
                });

            modelBuilder.Entity("GMC.Model.CourseMaster", b =>
                {
                    b.Property<string>("CourseId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AdditionalDegree")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("CouncilId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseDescription")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CourseNomeclature")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CourseShortCode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedOn")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedOn")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CourseId");

                    b.ToTable("tbl_CourseMaster");
                });

            modelBuilder.Entity("GMC.Model.DistrictMaster", b =>
                {
                    b.Property<string>("CountryId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(0);

                    b.Property<string>("AppCenter")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AppYN")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("CouncilId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(2);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DistrictId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(3);

                    b.Property<string>("DistrictName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Districtcount")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StateId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnOrder(1);

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("CountryId");

                    b.ToTable("tbl_district_master");
                });

            modelBuilder.Entity("GMC.Model.EducationInfo", b =>
                {
                    b.Property<string>("EducationID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ADSerialno")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("CertificateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CertificateNo")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CollegeID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CompletedAt")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CouncilCode")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("CouncilId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EducationName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IsIssued")
                        .HasColumnType("varchar(25)");

                    b.Property<string>("LedgerVerified")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MonthOfPassing")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PractitionerID")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubCode")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Subject")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TempCollege")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("TempEducationName")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("TempUniversity")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("TempYOP")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UniversityId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("YearOfPassing")
                        .HasColumnType("varchar(4)");

                    b.HasKey("EducationID");

                    b.ToTable("tbl_education_info");
                });

            modelBuilder.Entity("GMC.Model.FeesItems", b =>
                {
                    b.Property<int>("FeeItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeeItemId"));

                    b.Property<string>("CouncilId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FeeAmount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("FeeItemName")
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("FeeItemId");

                    b.ToTable("tbl_Fees_Items");
                });

            modelBuilder.Entity("GMC.Model.FeesReceipt", b =>
                {
                    b.Property<string>("AutoReceiptNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Cancel_Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Cancel_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Cancel_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Closing_Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Contra_Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CouncilId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CourseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Course_Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeeTmplID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinancialYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LedgerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextPymntDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Opening_Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProgramId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiptNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remited_NotRemited")
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime?>("Remitted_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("SubReceiptNo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TAX_Amnt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ipaddress")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("receipt")
                        .HasColumnType("int");

                    b.HasKey("AutoReceiptNo");

                    b.ToTable("tbl_Fees_Receipt");
                });

            modelBuilder.Entity("GMC.Model.FinancialYearMaster", b =>
                {
                    b.Property<int>("FinYearrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinYearrId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinancialYear")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedOn")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("YearCode")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("FinYearrId");

                    b.ToTable("tbl_Financial_Year_Master");
                });

            modelBuilder.Entity("GMC.Model.Financial_Year", b =>
                {
                    b.Property<int?>("AutoFinYearId")
                        .HasColumnType("int");

                    b.Property<string>("BankAccount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Closing_Balance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CouncilId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinancialYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opening_Balance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("YearCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YearID")
                        .HasColumnType("int");

                    b.ToTable("tbl_Financial_Year");
                });

            modelBuilder.Entity("GMC.Model.GMC.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CouncilId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firsttime_login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Site_Id")
                        .HasColumnType("int");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ipaddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("typeUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("usercount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_Users");
                });

            modelBuilder.Entity("GMC.Model.GenderMaster", b =>
                {
                    b.Property<string>("GenderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CouncilId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("GenderId");

                    b.ToTable("tbl_GenderMaster");
                });

            modelBuilder.Entity("GMC.Model.GroupLedgerMaster", b =>
                {
                    b.Property<string>("LedgerID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Certificate_Type")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CouncilId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("GroupID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LedgerCount")
                        .HasColumnType("int");

                    b.Property<string>("LedgerDescription")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LedgerName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LedgerStatus")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Type")
                        .HasColumnType("nchar(10)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("LedgerID");

                    b.ToTable("tbl_Group_LedgerMaster");
                });

            modelBuilder.Entity("GMC.Model.JCouncilMaster", b =>
                {
                    b.Property<string>("CouncilId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Banner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BannerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("city");

                    b.Property<string>("CouncilName")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phoneno")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShortCode")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("varchar(8)");

                    b.HasKey("CouncilId");

                    b.ToTable("tbl_J_Council_Master");
                });

            modelBuilder.Entity("GMC.Model.LedgerFeeItemLink", b =>
                {
                    b.Property<string>("FeeItemID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Certificate_Type")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CouncilId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("LedgerID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StateId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("FeeItemID");

                    b.ToTable("tbl_Ledger_FeeItem_Link");
                });

            modelBuilder.Entity("GMC.Model.NationalityMaster", b =>
                {
                    b.Property<string>("NationalityId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CouncilId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("NationalityId");

                    b.ToTable("tbl_masterNationality");
                });

            modelBuilder.Entity("GMC.Model.Practitioner", b =>
                {
                    b.Property<string>("PractitionerID")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Approve1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Approve1date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ApproveOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Approveby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BirthPlace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CME_Renw")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangeOfName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CouncilId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstLogin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromStatecode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HaveUserNamePassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsInliue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IsOnline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Obj_Ren")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PRC_payment_ReceiptNO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrcNoArchive")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrintStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proffession")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshRegistration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Registerstatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegistrationFor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Revwr_Editr_YN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpouseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Supplementary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Synch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TR_MBBS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TR_Non_MBBS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TR_SuperSpeciality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToStateCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Vote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearofRegistration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cme_photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("declaration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deletedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deleteyn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ipaddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("photo1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("photo2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("practsign")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tem_practitionerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tem_regNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("thumb")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PractitionerID");

                    b.ToTable("tbl_practitioner");
                });

            modelBuilder.Entity("GMC.Model.PractitionerEligiblity", b =>
                {
                    b.Property<string>("CouncilId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Eligibilty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EligibiltyId")
                        .HasColumnType("int");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime2");

                    b.ToTable("tbl_PractitionerEligiblity");
                });

            modelBuilder.Entity("GMC.Model.RazorPayPaymentAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ContactNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CouncilAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CouncilId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CouncilName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DummyReceiptNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FinYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LedgerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pay_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pids")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PractitionerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProgramName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceiptNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tbl_RayzorPay_Payment_Attempts");
                });

            modelBuilder.Entity("GMC.Model.RegistrationForMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CouncilId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("RegForName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tbl_RegistrationForMaster");
                });

            modelBuilder.Entity("GMC.Model.RenewalHistory", b =>
                {
                    b.Property<string>("RenewalID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AccountNo")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Amount")
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("AutoReceiptNo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Bank")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Comments")
                        .HasColumnType("varchar(300)");

                    b.Property<string>("CouncilId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DCIDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DCIRefNo")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("DD_ChequeDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DD_ChequeNO")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Fin_yr_code")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GoodStationdingRefNo")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("GroupID")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OnlineGoodStandingApprove")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PaymentFor")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PractitionerID")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("ReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiptNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RefNo")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("RenewalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SincID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasColumnType("char(1)");

                    b.Property<decimal?>("TAX_Amnt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionNo")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidUpto")
                        .HasColumnType("datetime2");

                    b.Property<string>("address")
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("councilRegdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("counciladdre")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("councilname")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("internship_from")
                        .HasColumnType("datetime2");

                    b.Property<string>("internship_institution")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime?>("internship_to")
                        .HasColumnType("datetime2");

                    b.Property<string>("slNo")
                        .HasColumnType("varchar(10)");

                    b.HasKey("RenewalID");

                    b.ToTable("tbl_renewal_history");
                });

            modelBuilder.Entity("GMC.Model.RenewalItems", b =>
                {
                    b.Property<string>("RenewalID")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CouncilId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FeeAmount")
                        .HasColumnType("int");

                    b.Property<int>("FeeItemId")
                        .HasColumnType("int");

                    b.Property<string>("PractitionerID")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("RenewalID");

                    b.ToTable("tbl_renewal_items");
                });

            modelBuilder.Entity("GMC.Model.RoleMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CouncilId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdateBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("tbl_Role_Master");
                });

            modelBuilder.Entity("GMC.Model.SiteSettings", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ButtonColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CardBg")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NavbarBg")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NavbarText")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SidebarActiveColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SidebarColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SidebarText")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TableBodyBg")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TableBodyText")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TableBtnColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TableHeaderBg")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TableHeaderText")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TextColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TopbarBg")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId");

                    b.ToTable("tbl_wesiteconfig");
                });

            modelBuilder.Entity("GMC.Model.StateMaster", b =>
                {
                    b.Property<string>("StateId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("StateId");

                    b.Property<string>("Active")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Active");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CountryId");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedOn");

                    b.Property<string>("StateName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("StateName");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UpdatedBy");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedOn");

                    b.HasKey("StateId");

                    b.ToTable("tbl_J_State_Master");
                });

            modelBuilder.Entity("GMC.Model.TitleMaster", b =>
                {
                    b.Property<int>("TitleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TitleId"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("TitleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TitleName");

                    b.HasKey("TitleId");

                    b.ToTable("tbl_title_master");
                });

            modelBuilder.Entity("GMC.Model.University", b =>
                {
                    b.Property<string>("UniversityId")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("university_id");

                    b.Property<string>("CouncilId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("StateId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UniversityCode")
                        .HasColumnType("varchar(5)")
                        .HasColumnName("university_code");

                    b.Property<string>("UniversityName")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("university_name");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("UniversityId");

                    b.ToTable("tbl_university");
                });
#pragma warning restore 612, 618
        }
    }
}
